//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Restaurant_Id { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public int Latitude { get; set; }
        public int Longitude { get; set; }
    }
}
